name: smart_fan_mqtt
description: A Flutter app to control fan speed, timer and read temperature via MQTT Cloud.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Thư viện MQTT
  mqtt_client: ^10.0.0

  # Material Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fan.png
Host: 099f0f049a6d49bca9614e32470c2276.s1.eu.hivemq.cloud
Port: 8884
Protocol: WebSocket Secure (WSS)

